### ISSUE TITLE
BingAIClient failed on cli

### ISSUE THREAD

**Issue by MichaelVandi** [waylaidwanderer/node-chatgpt-api#118]
I entered the configuration for bing in settings.js and got the following error.
Also which fields are absolutely necessary for the BingAIClient to work? I am not sure what to enter for proxy so I did `http://localhost:5000`

```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:14062:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BingAIClient.createNewConversation (file:///Users/mlv/Desktop/repos/node-chatgpt-api/src/BingAIClient.js:48:26)
    at async BingAIClient.sendMessage (file:///Users/mlv/Desktop/repos/node-chatgpt-api/src/BingAIClient.js:130:51)
    at async onMessage (file:///Users/mlv/Desktop/repos/node-chatgpt-api/bin/cli.js:167:26)
    at async file:///Users/mlv/Desktop/repos/node-chatgpt-api/bin/cli.js:100:1 {
  cause: TypeError: Cannot read properties of undefined (reading 'reason')
      at makeAppropriateNetworkError (node:internal/deps/undici/undici:6736:171)
      at httpNetworkFetch (node:internal/deps/undici/undici:13871:18)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async httpNetworkOrCacheFetch (node:internal/deps/undici/undici:13766:33)
      at async httpFetch (node:internal/deps/undici/undici:13618:37)
      at async schemeFetch (node:internal/deps/undici/undici:13546:18)
      at async node:internal/deps/undici/undici:13422:20
      at async mainFetch (node:internal/deps/undici/undici:13418:20)
}
```

**Comment by waylaidwanderer** [comment]
For Bing here is the bare minimum settings.js:

```JS
export default {
    bingAiClient: {
        cookies: 'your cookies here',
    },
    cliOptions: {
        clientToUse: 'bing',
    },
    storageFilePath: './cache.json',
}
```
