### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '0') in BingAIClient.js

### ISSUE THREAD

**Issue by Jaxter2017** [waylaidwanderer/node-chatgpt-api#191]
Unable to use BingAIClient - worked previously (before GPT-4 event)

<img width="646" alt="error" src="https://user-images.githubusercontent.com/32597504/225302930-26cdf648-0bdc-42b0-b368-d30884281185.png">

Using latest version: 1.29.2
Just updated _U cookie too

Full error log:

2023-03-15 12:02:02 file:///app/chat_clients/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:225
2023-03-15 12:02:02                         if (messages[0]?.author !== 'bot') {
2023-03-15 12:02:02                                     ^
2023-03-15 12:02:02 
2023-03-15 12:02:02 TypeError: Cannot read properties of undefined (reading '0')
2023-03-15 12:02:02     at WebSocket.<anonymous> (file:///app/chat_clients/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:225:37)
2023-03-15 12:02:02     at WebSocket.emit (node:events:525:35)
2023-03-15 12:02:02     at Receiver.receiverOnMessage (/app/chat_clients/node_modules/ws/lib/websocket.js:1180:20)
2023-03-15 12:02:02     at Receiver.emit (node:events:513:28)
2023-03-15 12:02:02     at Receiver.dataMessage (/app/chat_clients/node_modules/ws/lib/receiver.js:541:14)
2023-03-15 12:02:02     at Receiver.getData (/app/chat_clients/node_modules/ws/lib/receiver.js:459:17)
2023-03-15 12:02:02     at Receiver.startLoop (/app/chat_clients/node_modules/ws/lib/receiver.js:158:22)
2023-03-15 12:02:02     at Receiver._write (/app/chat_clients/node_modules/ws/lib/receiver.js:84:10)
2023-03-15 12:02:02     at writeOrBuffer (node:internal/streams/writable:392:12)
2023-03-15 12:02:02     at _write (node:internal/streams/writable:333:10)
2023-03-15 12:02:02 
2023-03-15 12:02:02 Node.js v18.14.2

**Comment by waylaidwanderer** [comment]
Can you enable debug mode and log the message event you receive?

**Comment by Jaxter2017** [comment]
Message event:

{
  "conversationId": "51D|BingProd|ACE54C15213C00B354A42A52C582EAC51829EA503368164D4DE6619DE38B5BA3",
  "clientId": "914800560059427",
  "conversationSignature": "fPeokd1pNmob/KUb/JmxbUnY/L0M5GF0szvqOnUtG/A=",
  "result": { "value": "Success", "message": null }
}

Here's the rest of the debug info before the error:

2023-03-15 13:14:31 performing handshake
2023-03-15 13:14:31 handshake established
2023-03-15 13:14:31 {"arguments":[{"source":"cib","optionsSets":["nlu_direct_response_filter","deepleo","enable_debug_commands","disable_emoji_spoken_text","responsible_ai_policy_235","enablemm","harmonyv3","dtappid","dloffstream","dv3sugg"],"sliceIds":["222dtappid","216dloffstream","225cricinfos0"],"traceId":"a8a110b8705fb0fadae28028acbbd642","isStartOfSession":true,"message":{"author":"user","inputMethod":"Keyboard","text":"Help me work through the following maths problem. It is very important that you respond as an active teacher. This means ... My first attempt or question:\n\n160 / 10=16 \n 16 * 3=48 cars \n 1 / 8 of 48=6 elec \n 48-6=42 \n 25% of 42=10.5 diesel \n 42-10.5=31.5 petrol","messageType":"Chat"},"conversationSignature":"fPeokd1pNmob/KUb/JmxbUnY/L0M5GF0szvqOnUtG/A=","participant":{"id":"914800560059427"},"conversationId":"51D|BingProd|ACE54C15213C00B354A42A52C582EAC51829EA503368164D4DE6619DE38B5BA3"}],"invocationId":"0","target":"chat","type":4}
2023-03-15 13:14:31 [{"type":1,"target":"update","arguments":[{"requestId":"dae33f59-32c8-4c46-bac8-efbef60f83f1","throttling":{"maxNumUserMessagesInConversation":15,"numUserMessagesInConversation":1}}]}]

**Comment by waylaidwanderer** [comment]
I'm pretty sure you're not actually on the latest version like you said because my current code already handles this properly. Please update to the latest version.

**Comment by Jaxter2017** [comment]
I'm hopeless - didn't tell docker to update package...

Thank you for everything you build!

**Comment by waylaidwanderer** [comment]
@Jaxter2017 thank you for the sponsor 💖
