### ISSUE TITLE
Unhandled Dependency Failure

### ISSUE THREAD

**Issue by Naozumi520** [waylaidwanderer/node-chatgpt-api#227]
```
Error: InternalError: Unhandled Dependency Failure: ChatGpt
    at WebSocket.<anonymous> (file:///Users/naozumi/Desktop/NaoyukiV2/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:431:36)
    at WebSocket.emit (node:events:525:35)
    at Receiver.receiverOnMessage (/Users/naozumi/Desktop/NaoyukiV2/node_modules/ws/lib/websocket.js:1184:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/Users/naozumi/Desktop/NaoyukiV2/node_modules/ws/lib/receiver.js:541:14)
    at Receiver.getData (/Users/naozumi/Desktop/NaoyukiV2/node_modules/ws/lib/receiver.js:459:17)
    at Receiver.startLoop (/Users/naozumi/Desktop/NaoyukiV2/node_modules/ws/lib/receiver.js:158:22)
    at Receiver._write (/Users/naozumi/Desktop/NaoyukiV2/node_modules/ws/lib/receiver.js:84:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    ```

**Comment by Naozumi520** [comment]
This issue is very weird. Since I'm using bing and not ChatGPT.

**Comment by BarryAllen-Arrow** [comment]
> This issue is very weird. Since I'm using bing and not ChatGPT.

are you using jailbreak version? I was having this problem too

**Comment by Naozumi520** [comment]
Yeah! I'm using the jailbreak conversation.

**Comment by BarryAllen-Arrow** [comment]
> Yeah! I'm using the jailbreak conversation.

I have no idea why would this problem happen... hope waylaid will see this issue soon XD
