### ISSUE TITLE
ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by MadeBugs** [waylaidwanderer/node-chatgpt-api#27]
ReferenceError: fetch is not defined
    at file:///Users/newuser/Documents/chatgpt/node-chatgpt-api/node_modules/@fortaine/fetch-event-source/lib/esm/fetch.js:46:85
    at new Promise (<anonymous>)
    at fetchEventSource (file:///Users/newuser/Documents/chatgpt/node-chatgpt-api/node_modules/@fortaine/fetch-event-source/lib/esm/fetch.js:18:12)
    at file:///Users/newuser/Documents/chatgpt/node-chatgpt-api/src/ChatGPTClient.js:77:27
    at new Promise (<anonymous>)
    at ChatGPTClient.getCompletion (file:///Users/newuser/Documents/chatgpt/node-chatgpt-api/src/ChatGPTClient.js:74:20)
    at ChatGPTClient.sendMessage (file:///Users/newuser/Documents/chatgpt/node-chatgpt-api/src/ChatGPTClient.js:160:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async onMessage (file:///Users/newuser/Documents/chatgpt/node-chatgpt-api/bin/cli.js:142:26)
    at async file:///Users/newuser/Documents/chatgpt/node-chatgpt-api/bin/cli.js:83:1

**Comment by waylaidwanderer** [comment]
What version of Node.js are you using?

I tried to push a fix for you. Can you pull the latest version and try again?

**Comment by MadeBugs** [comment]
`% node -v
v16.15.0`

this bug is fix;👍

**Comment by waylaidwanderer** [comment]
Great

**Comment by baogaodawang** [comment]
how to fix it？

**Comment by waylaidwanderer** [comment]
@baogaodawang Make sure you're on the latest version (>= 1.33.0) and preferably on Node >= 18 as well.
