### ISSUE TITLE
Unhandled Dependency Failure: DeepLeo

### ISSUE THREAD

**Issue by ztc1997** [waylaidwanderer/node-chatgpt-api#270]
**Describe the bug**
Error: InternalError: Unhandled Dependency Failure: DeepLeo
    at WebSocket.<anonymous> (file:///.../node-chatgpt-api/src/BingAIClient.js:453:36)
    at WebSocket.emit (node:events:524:35)
    at Receiver.receiverOnMessage (/.../node-chatgpt-api/node_modules/ws/lib/websocket.js:1184:20)
    at Receiver.emit (node:events:512:28)
    at Receiver.dataMessage (/.../node-chatgpt-api/node_modules/ws/lib/receiver.js:541:14)
    at Receiver.getData (/.../node-chatgpt-api/node_modules/ws/lib/receiver.js:459:17)
    at Receiver.startLoop (/.../node-chatgpt-api/node_modules/ws/lib/receiver.js:158:22)
    at Receiver._write (/.../node-chatgpt-api/node_modules/ws/lib/receiver.js:84:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)

**To Reproduce**
Use bing jailbreak mode

**Expected behavior**
success return answer

**Screenshots**

**Node.js version (please complete the following information):**
 - OS: [Debian 11]
 - Version [19]

**Package version (please complete the following information):**
 - [1.33.3]

**Additional context**

**Comment by waylaidwanderer** [comment]
This is an error from Bing's end. Unless it's reproducible, it's not a valid bug.

**Comment by ztc1997** [comment]
High probability of reproducing when the dialogue exceeds over 30 rounds.
