### ISSUE TITLE
Unhandled Dependency Failure: DeepLeo

### ISSUE THREAD

**Issue by andrewson253** [waylaidwanderer/node-chatgpt-api#282]
```
Error: InternalError: Unhandled Dependency Failure: DeepLeo
    at WebSocket.<anonymous> (file:///D:/Tools/node-chatgpt-api-main/src/BingAIClient.js:438:36)
    at WebSocket.emit (node:events:525:35)
    at Receiver.receiverOnMessage (D:\Tools\node-chatgpt-api-main\node_modules\ws\lib\websocket.js:1184:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (D:\Tools\node-chatgpt-api-main\node_modules\ws\lib\receiver.js:541:14)
    at Receiver.getData (D:\Tools\node-chatgpt-api-main\node_modules\ws\lib\receiver.js:459:17)
    at Receiver.startLoop (D:\Tools\node-chatgpt-api-main\node_modules\ws\lib\receiver.js:158:22)
    at Receiver._write (D:\Tools\node-chatgpt-api-main\node_modules\ws\lib\receiver.js:84:10)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
```
Wonder why it happened

**Comment by waylaidwanderer** [comment]
Please open a proper bug report next time. Additionally, I'm pretty sure there were previous issues opened about this. Please use the search function.
