### ISSUE TITLE
Agent error

### ISSUE THREAD

**Issue by zhouxinhao1208** [waylaidwanderer/node-chatgpt-api#349]
TypeError: HttpsProxyAgent is not a constructor
    at file:///C:/Users/Administrator/Desktop/node-chatgpt-api/src/BingAIClient.js:96:25
    at new Promise (<anonymous>)
    at BingAIClient.createWebSocketConnection (file:///C:/Users/Administrator/Desktop/node-chatgpt-api/src/BingAIClient.js:93:16)
    at BingAIClient.sendMessage (file:///C:/Users/Administrator/Desktop/node-chatgpt-api/src/BingAIClient.js:280:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async onMessage (file:///C:/Users/Administrator/Desktop/node-chatgpt-api/bin/cli.js:170:26)
    at async file:///C:/Users/Administrator/Desktop/node-chatgpt-api/bin/cli.js:97:1
Type "!" to access the command menu.
? Write a message:
  ​

**Comment by andrewson253** [comment]
I tried this, it works
https://stackoverflow.com/questions/53419610/how-do-i-use-a-proxy-with-node-and-esm

**Comment by hupimaodaren** [comment]
I can give you a chinese answer。
我遇到了同样的错误，确认是  https-proxy-agent升级后的不兼容问题，你可以删掉重新安装老版本试一下，我的已经回复正常了

**Comment by Czx1235** [comment]
Just like @andrewson253 say.
Open ./src/BingAIClient.js
At the 6 line
`import HttpsProxyAgent from 'https-proxy-agent';`
change it to
`import {HttpsProxyAgent} from 'https-proxy-agent';`
