### ISSUE TITLE
/turing/conversation/create: failed to parse response body.

### ISSUE THREAD

**Issue by huoshenw** [waylaidwanderer/node-chatgpt-api#362]
at BingAIClient.createNewConversation (file:///var/chatgpt-api/src/BingAIClient.js:88:19)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async BingAIClient.sendMessage (file:///var/chatgpt-api/src/BingAIClient.js:184:51)
at async Object.<anonymous> (file:///var/chatgpt-api/bin/server.js:105:18)

**Comment by huoshenw** [comment]
Microsoft's official issue
