### ISSUE TITLE
Connection closed with an error.

### ISSUE THREAD

**Issue by joshholly** [waylaidwanderer/node-chatgpt-api#395]
**Describe the bug**
The websocket closed with an error and I am not sure why. 

**To Reproduce**
1. Send message to jailbroken sydney

**Expected behavior**
A response

Error

```
Error: Connection closed with an error.
    at WebSocket.<anonymous> (file:///Users/wafflehacker/Sites/chatgpt-clone/node_modules/@waylaidwanderer/chatgpt-api/src/BingAIClient.js:483:32)
    at WebSocket.emit (node:events:525:35)
    at Receiver.receiverOnMessage (/Users/wafflehacker/Sites/chatgpt-clone/node_modules/ws/lib/websocket.js:1184:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/Users/wafflehacker/Sites/chatgpt-clone/node_modules/ws/lib/receiver.js:541:14)
    at Receiver.getData (/Users/wafflehacker/Sites/chatgpt-clone/node_modules/ws/lib/receiver.js:459:17)
    at Receiver.startLoop (/Users/wafflehacker/Sites/chatgpt-clone/node_modules/ws/lib/receiver.js:158:22)
    at Receiver._write (/Users/wafflehacker/Sites/chatgpt-clone/node_modules/ws/lib/receiver.js:84:10)
```

**Comment by joshholly** [comment]
So if I re-generate the previous response, it will work. However, when I try to send it a new response the websocket connection closes.

**Comment by waylaidwanderer** [comment]
Did you enable debug mode to try to see if there's any more information?

**Comment by joshholly** [comment]
How do I enable debug mode? So I noticed it happens after 121 messages. If I delete some messages from MongoDB, it does just fine.

**Comment by joshholly** [comment]
Ah, so it looks like you can have up to a certain amount of tokens before it cuts you off. It's way more than 20 mesages, but yeah. I tried to manaully paste the chat history and it still errored out in a new chat. So it seems like something on bing's end that probably can't be fixed.

**Comment by joshholly** [comment]
Is there something I can put in the code to only retreive the last 110 messages?

**Comment by waylaidwanderer** [comment]
I think the model is reaching a token limit. If we can figure out what the number of tokens is that causes the issue, we can implement an algorithm to trim older messages that would exceed this limit.

**Comment by fcgca** [comment]
{
  conversationId: '51D|BingProd|7E0C08EA639C06E65B8458CD295B873BC81CC8447DFC9F120EA36E639ADA59A',
  clientId: '0A2D1B00179F6B2D0672081316B6A4D',
  conversationSignature: 'dN4i6uLgggmVjKa0rQLLi1feWxRwYzZVI8OGI02ySU=',
  result: { value: 'Success', message: null }
}
performing handshake
handshake established
{"arguments":[{"source":"cib","optionsSets":["nlu_direct_response_filter","deepleo","disable_emoji_spoken_text","responsible_ai_po}

[{"type":7,"error":"Connection closed with an error.","allowReconnect":true}]
