### ISSUE TITLE
On the very first request "Slow Down" Error for chatGptBrowserClient 

### ISSUE THREAD

**Issue by beshoo** [waylaidwanderer/node-chatgpt-api#506]
```
   ╔═══════════════╗
   ║  ChatGPT CLI  ║
   ╚═══════════════╝

Type "!" to access the command menu.
? Write a message: hi
Error: Failed to send message. HTTP 429 - {"error": "slow down"}
    at onopen (file:///D:/whatsapp/gpt_api/src/ChatGPTClient.js:206:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async create (file:///D:/whatsapp/gpt_api/node_modules/@waylaidwanderer/fetch-event-source/lib/esm/fetch.js:53:17) {
  status: 429,
  json: { error: 'slow down' }
}
Type "!" to access the command menu.
? Write a message:
```

**Comment by ChungVut** [comment]
same here. Have you solved it?
