### ISSUE TITLE
local Bing correctly, but server  does not work

### ISSUE THREAD

**Issue by yuwangi** [waylaidwanderer/node-chatgpt-api#84]
I'm running into some issues,
When I deploy locally bing returns correctly,
When I deploy on the server but no results are returned,
Have you ever encountered this? I guarantee the code is exactly the same

**Comment by waylaidwanderer** [comment]
On the server, try doing a curl GET request to `https://www.bing.com/turing/conversation/create`. You should see `Sorry, you are not allowed to access this service` if it works, but maybe Bing blocks some IPs from VPS networks entirely.

**Comment by yuwangi** [comment]
I tried it and found that my host is cn.bing.com, so can I support the configuration of host?
![1676524981980](https://user-images.githubusercontent.com/13346477/219275846-ded1321a-63e6-4e50-9875-0c57fdb33606.png)

**Comment by yuwangi** [comment]
I tried it and found that my host is cn.bing.com, so can I support the configuration of host?
![1676524981980](https://user-images.githubusercontent.com/13346477/219275846-ded1321a-63e6-4e50-9875-0c57fdb33606.png)

**Comment by waylaidwanderer** [comment]
@yuwangi Can you first turn on debug mode for the Bing client and try it on the server?

**Comment by ndwzy** [comment]
国内ip会强制跳转cn.bing.com不支持bingAI  你可以尝试host能否解决 如果不行就需要翻墙

**Comment by yuwangi** [comment]
@waylaidwanderer   
I tried it, changing the server code to cn.bing.com is ok.
I originally wanted to try to use nginx reverse proxy directly, but the cookie and authentication information will be discarded, so I hope to support host customization, thks

**Comment by eu09** [comment]
In setting.js I defined the  host: 'https://cn.bing.com',
But it is not work
ReferenceError: host is not defined
    at BingAIClient.createNewConversation (file:///var/chatgpt-api/src/BingAIClient.js:19:41)
    at BingAIClient.sendMessage (file:///var/chatgpt-api/src/BingAIClient.js:120:62)
    at Object.<anonymous> (file:///var/chatgpt-api/bin/server.js:97:31)
    at preHandlerCallback (/var/chatgpt-api/node_modules/fastify/lib/handleRequest.js:128:37)
    at preValidationCallback (/var/chatgpt-api/node_modules/fastify/lib/handleRequest.js:112:5)
    at handler (/var/chatgpt-api/node_modules/fastify/lib/handleRequest.js:76:7)
    at /var/chatgpt-api/node_modules/fastify/lib/contentTypeParser.js:192:9
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at done (/var/chatgpt-api/node_modules/fastify/lib/contentTypeParser.js:186:14)
    at Parser.defaultJsonParser [as fn] (/var/chatgpt-api/node_modules/fastify/lib/contentTypeParser.js:292:5)
ReferenceError: host is not defined
    at BingAIClient.createNewConversation (file:///var/chatgpt-api/src/BingAIClient.js:19:41)
    at BingAIClient.sendMessage (file:///var/chatgpt-api/src/BingAIClient.js:120:62)
    at Object.<anonymous> (file:///var/chatgpt-api/bin/server.js:97:31)
    at preHandlerCallback (/var/chatgpt-api/node_modules/fastify/lib/handleRequest.js:128:37)
    at preValidationCallback (/var/chatgpt-api/node_modules/fastify/lib/handleRequest.js:112:5)
    at handler (/var/chatgpt-api/node_modules/fastify/lib/handleRequest.js:76:7)
    at /var/chatgpt-api/node_modules/fastify/lib/contentTypeParser.js:192:9
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at done (/var/chatgpt-api/node_modules/fastify/lib/contentTypeParser.js:186:14)
    at Parser.defaultJsonParser [as fn] (/var/chatgpt-api/node_modules/fastify/lib/contentTypeParser.js:292:5)

**Comment by waylaidwanderer** [comment]
@eu09 Oops, thanks for catching that. Fixed in 1.17.6.
