### ISSUE TITLE
fetch failed

### ISSUE THREAD

**Issue by qq11272658** [waylaidwanderer/node-chatgpt-api#91]
package version: 1.17.4
node version: 16.16.0
model: 'text-davinci-003'

TypeError: fetch failed
    at fetch (/root/xiaoqiang/node-chatgpt-api/node_modules/undici/index.js:113:13)
    at async ChatGPTClient.getCompletion (file:///root/xiaoqiang/node-chatgpt-api/src/ChatGPTClient.js:144:26)
    at async ChatGPTClient.sendMessage (file:///root/xiaoqiang/node-chatgpt-api/src/ChatGPTClient.js:202:28)
    at async Object.<anonymous> (file:///root/xiaoqiang/node-chatgpt-api/bin/server.js:97:18) {
  cause: HeadersTimeoutError: Headers Timeout Error
      at Timeout.onParserTimeout [as callback] (/root/xiaoqiang/node-chatgpt-api/node_modules/undici/lib/client.js:906:28)
      at Timeout.onTimeout [as _onTimeout] (/root/xiaoqiang/node-chatgpt-api/node_modules/undici/lib/timers.js:18:13)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7) {
    code: 'UND_ERR_HEADERS_TIMEOUT'
  }
}

**Comment by sirlaurie** [comment]
I pulled the last code, it's same error.

**Comment by waylaidwanderer** [comment]
@sirlaurie @qq11272658 are you using streaming mode? Is there a specific message/prompt that you can reproduce this issue with?

**Comment by sirlaurie** [comment]
> @sirlaurie @qq11272658 are you using streaming mode? Is there a specific message/prompt that you can reproduce this issue with?

I didn't use stream mode, all options are default except api key. 

here is the prompt which I using every time but error occurred: "使用python fastapi开发后端, 遇到耗时很长的计算, 有哪些比较好的处理方法?"

**Comment by qq11272658** [comment]
> 

post params stream is false

**Comment by qq11272658** [comment]
> @sirlaurie @qq11272658 are you using streaming mode? Is there a specific message/prompt that you can reproduce this issue with?

post params stream is false

**Comment by waylaidwanderer** [comment]
I believe this should now be fixed in 1.20.6.
