### ISSUE TITLE
i updated but get this errors

### ISSUE THREAD

**Issue by newdots** [waylaidwanderer/node-chatgpt-api#99]
[root@localhost node-chatgpt-api]# node diy/server.js --setting=/home/dev/node-chatgpt-api/settings.js  settings.js
conversation:req-1
Empty <[Object: null prototype] {}> {
  m: '',
  conversationId: 'kefu2',
  tk: 'blchat',
  stream: 'true',
  message: '你好',
  user: '2cef43e6-eac3-49fd-9b2b-6e480893dad0'
}
TypeError: Cannot read properties of null (reading 'conversation_id')
    at ChatGPTBrowserClient.sendMessage (file:///home/dev/node-chatgpt-api/src/ChatGPTBrowserClient.js:180:33)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.<anonymous> (file:///home/dev/node-chatgpt-api/diy/server.js:147:18)
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot render headers after they are sent to the client
    at new NodeError (node:internal/errors:372:5)
    at ServerResponse.writeHead (node:_http_server:313:13)
    at /home/dev/node-chatgpt-api/node_modules/fastify/lib/error-handler.js:41:19
    at fallbackErrorHandler (/home/dev/node-chatgpt-api/node_modules/fastify/lib/error-handler.js:130:3)
    at handleError (/home/dev/node-chatgpt-api/node_modules/fastify/lib/error-handler.js:33:5)
    at onErrorHook (/home/dev/node-chatgpt-api/node_modules/fastify/lib/reply.js:742:5)
    at _Reply.Reply.send (/home/dev/node-chatgpt-api/node_modules/fastify/lib/reply.js:133:5)
    at /home/dev/node-chatgpt-api/node_modules/fastify/lib/wrapThenable.js:43:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

**Comment by userluoc** [comment]
和我一样

**Comment by waylaidwanderer** [comment]
Handled properly with `@waylaidwanderer/chatgpt-api@1.20.3`. It seems to be caused by an invalid access token.

**Comment by clippers1** [comment]
There is a long delay of answer, which using ChatGPTBrowserClient. Average  1min in chinese

**Comment by waylaidwanderer** [comment]
@clippers1 Use stream mode if you don't want to wait so long. It's the same speed as using chat.openai.com.
